name: Generate Stats Card

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jstrieb/github-stats-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}